name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [18.x, 20.x, 22.x, 24.x]
        
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install system dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential python3
    
    - name: Install system dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        # Ensure we have the latest command line tools
        xcode-select --install || true
        # Install Python if needed
        which python3 || brew install python3
    
    - name: Install system dependencies (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        # Install Python and build tools
        choco install python3 -y
        npm install -g windows-build-tools || echo "Build tools installation attempted"
    
    - name: Install dependencies
      run: npm install
    
    - name: Build native module
      run: npm run build
      
    - name: Run tests
      run: npm test
      
    - name: Run linting
      run: npm run lint
      
    - name: Test module loading
      run: node -e "console.log('Testing module load...'); const m = require('./index.js'); console.log('✓ Module loaded successfully');"

  # Separate job for testing with different mbedTLS configurations
  compatibility-test:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Use Node.js 24.x
      uses: actions/setup-node@v4
      with:
        node-version: '24.x'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential python3
    
    - name: Install dependencies
      run: npm install
    
    - name: Build and test with debug output
      run: |
        echo "Building with debug information..."
        npm run build
        echo "Running comprehensive tests..."
        npm test
        echo "Testing example usage..."
        cd examples && node echo.js --help || echo "Example script executed"

  # Code quality and security checks
  quality:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Use Node.js 24.x
      uses: actions/setup-node@v4
      with:
        node-version: '24.x'
    
    - name: Install dependencies
      run: npm install
    
    - name: Run linting
      run: npm run lint
    
    - name: Check for security vulnerabilities
      run: npm audit --audit-level moderate
    
    - name: Check package.json validity
      run: npm ls || echo "Dependency tree checked"
    
    - name: Verify package contents
      run: |
        echo "Checking essential files..."
        test -f package.json && echo "✓ package.json found"
        test -f index.js && echo "✓ index.js found"
        test -f socket.js && echo "✓ socket.js found"
        test -f binding.gyp && echo "✓ binding.gyp found"
        test -d mbedtls && echo "✓ mbedtls directory found"
        test -d test && echo "✓ test directory found"
